# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# myexplosion.py
# Created on: 2019-02-12 11:37:37.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: myexplosion <Input_Features> <Distance__value_or_field_> <Feature_Layer> <Intersect__2_> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
explosion_location = arcpy.GetParameterAsText(0)

explosion_distance = arcpy.GetParameterAsText(1)

building_shpfile = arcpy.GetParameterAsText(2)

Intersect__2_ = arcpy.GetParameterAsText(3)
#if Intersect__2_ == '#' or not Intersect__2_:
#    Intersect__2_ = "\\\\ds.leeds.ac.uk\\student\\student13\\gy17m2a\\ArcGIS\\Default.gdb\\Intersect" # provide a default value if unspecified
#Intersect__2_ = ""E:/Msc/Advanced-Programming/Practical1"3\\gy17m2a\\ArcGIS\\Default.gdb\\Intersect" # provide a default value if unspecified

# Local variables:
Output_Feature_Class = "intermediate"
if arcpy.Exists(Output_Feature_Class):
    arcpy.management.Delete(Output_Feature_Class)


# Process: Buffer
arcpy.Buffer_analysis(explosion_location, Output_Feature_Class, explosion_distance , "FULL", "ROUND", "NONE", "", "PLANAR")

# Process: Intersect
arcpy.Intersect_analysis([building_shpfile ,Output_Feature_Class,], Intersect__2_, "ALL", "", "INPUT")

